version : '3'

services:
	mongo:
		image: mongo
	container_name: mongo
	restart: always
	ports:
		- "27017:27017"
	volumenes:
		- c:/data/db:data/db
	networks:
			- mongo-networks

	mongo-express:
		image: mongo-express:0.54
		container_name: mongo-express
		ports:
			- "8081:8081"
		depends_on:
			- mongo
		enviroment:
			ME_CONFIG_BASICAUTH_USERNAME: root
			ME_CONFIG_BASICAUTH_PASSWORD: root
			ME_CONFIG_MONGODB_PORT: 27017
		links:
			- mongo
		networks:
			- mongo-networks
	networks:
		mongo-networks:
		driver:bridge